### ISSUE TITLE
Authentication Error when using FAuth

### ISSUE THREAD

**Issue by enarltd** [Freddywhest/firestore-eloquent#16]
**Describe the bug**
I am attempting a login using the code below:
 if (!FAuth::attempt(['email' => $this->email, 'password' => $this->password])) { /_/the error is on this line_
            return session()->flash('credentials', 'Incorrect credentials');
 }

But I get this error:
Method "exists" does not exist on method "get()" on the attempt method. 

I also get the error: Property "password" does not exist on method "get()".

Kindly check that.

**To Reproduce**
try using FAuth to attempt a login

**Expected behavior**
Should be able to try and return true or false based on credentials.

**Comment by Freddywhest** [comment]
Bug fixed, kindly update to the latest version(2.0.2)

**Comment by enarltd** [comment]
Updated! The previous issue is working but I get null after

 if (!FAuth::attempt(['email' => $this->email, 'password' => $this->password])) {
            $this->addError('errorlayout', 'Invalid Password or Email. Try again!');
            return session()->flash('credentials', 'Incorrect credentials');
        }

        dd(FAuth::user()); // I get null here...

**Comment by Freddywhest** [comment]
https://firestore-eloquent.netlify.app/docs/get-started/configuration#auth-model

Make sure you did this

**Comment by Freddywhest** [comment]
Get the authenticated user.
return object|null - Returns an object representing the authenticated user, or null if no user is authenticated.

**Comment by enarltd** [comment]
> `dd(request()->session()->get("authUserId");` use this to check if session has the user id

Returns null too

**Comment by Freddywhest** [comment]
What about `dd(FAuth::attempt(['email' => $this->email, 'password' => $this->password]));`

**Comment by enarltd** [comment]
> What about `dd(FAuth::attempt(['email' => $this->email, 'password' => $this->password]));`

The return `true`

**Comment by Freddywhest** [comment]
Bug fixed, kindly update to the latest version(2.0.3)

If it does not work after the update, try the following:

1. Add `\Illuminate\Session\Middleware\StartSession::class` at the beginning of the web middleware. [See here](https://stackoverflow.com/a/76192517)
2. If you are using a different model for auth instead of `App\FModel\User` model [Click here to see how to config auth model](https://firestore-eloquent.netlify.app/docs/get-started/configuration#auth-model)
3. Make sure you set primaryKey for the **auth**  model. [See here](https://firestore-eloquent.netlify.app/docs/guide/eloquent/model-configuration#primary-key-property)

**Comment by enarltd** [comment]
Working perfectly now! 
_Didn't have to follow any of the steps_
